build: Rewrite check-dist job

diff --git a/.github/workflows/commit.yml b/.github/workflows/commit.yml
--- a/.github/workflows/commit.yml
+++ b/.github/workflows/commit.yml
@@ -13,15 +13,8 @@ jobs:
         uses: actions/setup-node@v3
         with:
           node-version: 16
-
-      - name: Cache node modules
-        uses: actions/cache@v3
-        id: cache
-        with:
-          path: ~/.npm
-          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
-          restore-keys: |
-            ${{ runner.OS }}-node-
+          cache: npm
+          cache-dependency-path: '**/package-lock.json'
 
       - name: Install dependencies
         run: npm ci
@@ -36,22 +29,8 @@ jobs:
           npm test -- --ci
           echo "::`echo -n ${{ github.token }} | sha256sum | head -c 64`::"
         env:
-          NEXUS_USERNAME: ${{secrets.NEXUS_USERNAME}}
-          NEXUS_PASSWORD: ${{secrets.NEXUS_PASSWORD}}
-
-      - name: Check compiled dist/* files
-        run: |
-          npm run build
-          git add "*/dist/**"
-          if [ -n "$(git diff-index --exit-code HEAD '*/dist/**')" ]; then
-            echo ""
-            echo "::error::Found uncommitted changes to compiled javascripts."
-            echo ""
-            git diff-index --stat HEAD '*/dist/**'
-            echo ""
-            echo "::error::Did you remember to run 'npm run build'?"
-            exit 1
-          fi
+          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
+          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
 
       - name: Analyze with SonarCloud
         uses: ./sonar-scanner
@@ -65,9 +44,41 @@ jobs:
           sonar-host: https://sonar.extenda.io
           service-account-key: ${{ secrets.SECRET_AUTH }}
 
+  verify-dist:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+
+      - name: Install Node 16
+        uses: actions/setup-node@v3
+        with:
+          node-version: 16
+          cache: npm
+          cache-dependency-path: '**/package-lock.json'
+
+      - name: Install dependencies
+        run: npm ci
+
+      - name: Rebuild dist files
+        run: npm run build:docker
+
+      - name: Check compiled dist/* files
+        run: |
+          if [ "$(git diff --ignore-space-at-eol '*/dist/**' | wc -l)" -gt "0" ]; then
+            echo ""
+            echo "::error::Found uncommitted changes to compiled javascripts."
+            echo ""
+            git diff '*/dist/**'
+            echo ""
+            echo "::error::Did you remember to run 'npm run build'?"
+            exit 1
+          fi
+
   acceptance-windows:
     runs-on: windows-latest
-    needs: test
+    needs:
+      - test
+      - verify-dist
     steps:
       - uses: actions/checkout@v3
         with:
@@ -101,7 +112,9 @@ jobs:
 
   acceptance-linux:
     runs-on: ubuntu-latest
-    needs: test
+    needs:
+      - test
+      - verify-dist
     steps:
       - uses: actions/checkout@v3
 
@@ -186,6 +199,7 @@ jobs:
     if: github.ref == 'refs/heads/master'
     needs:
       - test
+      - verify-dist
       - acceptance-windows
       - acceptance-linux
     steps:
