chore: Test acceptance test on ubuntu 26.04

diff --git a/.github/workflows/commit.yml b/.github/workflows/commit.yml
--- a/.github/workflows/commit.yml
+++ b/.github/workflows/commit.yml
@@ -256,6 +256,116 @@ jobs:
           echo VERSION=${{ steps.version.outputs.version }}
           echo RELEASE_TAG=${{ steps.version.outputs.release-tag }}
 
+  acceptance-linux-ubuntu-26:
+    runs-on: ubuntu-26.04
+    needs:
+      - verify-dist
+    permissions:
+      contents: read
+      id-token: write
+    steps:
+      - uses: actions/checkout@v7
+
+      - name: Install Java
+        uses: actions/setup-java@v6.0.1
+        with:
+          distribution: temurin
+          java-version: 25
+
+      - name: Run Maven (no POM)
+        uses: ./maven
+        with:
+          args: --version
+          service-account-key: ${{ secrets.SECRET_AUTH }}
+
+      - name: Run Maven action dependency:get from Nexus
+        uses: ./maven
+        with:
+          args: dependency:get -Dartifact=se.extenda.maven:commonpom:2.5.1:pom
+          service-account-key: ${{ secrets.SECRET_AUTH }}
+
+      - name: Run Maven CLI
+        run: mvn dependency:get -Dartifact=se.extenda.maven:commonpom:2.5.1:pom
+
+      - name: GCP Secret Manager
+        uses: ./gcp-secret-manager
+        with:
+          service-account-key: ${{ secrets.SECRET_AUTH }}
+          secrets: |
+            TEST_TOKEN: sonarqube-token
+            TEST2_TOKEN: sonarqube-token
+
+      - name: Assert GCP secrets
+        run: |
+          if [ -n "$TEST_TOKEN" ]; then
+            echo "Secret successfully set to env"
+          else
+            echo "Failed to set secret to env"
+            exit 1
+          fi
+
+          if [ "$TEST_TOKEN" = "$TEST2_TOKEN" ]; then
+            echo "Secret matches expectation"
+          else
+            echo "Second secret does not match"
+            exit 1
+          fi
+
+      - name: Setup Gcloud
+        uses: ./setup-gcloud
+        id: gcloud
+        with:
+          service-account-key: ${{ secrets.SECRET_AUTH }}
+
+      - name: GCP Secret Manager Does Not Interfere with Gcloud
+        uses: ./gcp-secret-manager
+        with:
+          service-account-key: ${{ secrets.SECRET_AUTH_WIF }}
+          secrets: |
+            TEST3_TOKEN: sonarqube-token
+            TEST4_TOKEN: sonarqube-token
+
+      - name: Test Gcloud
+        run: |
+          gcloud --version
+          gsutil --version
+          if [ "${{ steps.gcloud.outputs.project-id }}" == "" ]; then
+            echo "Failed to set project-id"
+            exit 1
+          fi
+          projects=$(gcloud projects list --format='value(projectId)')
+          echo "$projects"
+          if [ -z "$projects" ]; then
+            echo "Project list is empty"
+            exit 1
+          fi
+
+      - name: Setup Terraform
+        uses: ./setup-terraform
+        with:
+          terraform-version: 0.11.14
+          terragrunt-version: 0.23.3
+
+      - name: Test Terraform
+        run: |
+          terraform -version
+          if [[ "$(terraform -version)" != *"v0.11.14"* ]]; then
+            echo "Did not find expected terraform v0.11.14"
+            which -a terraform
+            exit 1
+          fi
+          terragrunt -version
+
+      - name: Conventional version
+        uses: ./conventional-version
+        id: version
+
+      - name: Print version
+        run: |
+          echo VERSION=${{ steps.version.outputs.version }}
+          echo RELEASE_TAG=${{ steps.version.outputs.release-tag }}
+
+
   release:
     runs-on: ubuntu-latest
     if: github.ref == 'refs/heads/master'
