build: Test secret-manager on Windows

diff --git a/.github/workflows/commit.yml b/.github/workflows/commit.yml
--- a/.github/workflows/commit.yml
+++ b/.github/workflows/commit.yml
@@ -109,6 +109,39 @@ jobs:
           echo VERSION=${{ steps.version.outputs.version }}
           echo RELEASE_TAG=${{ steps.version.outputs.release-tag }}
 
+      - name: GCP Secret Manager
+        uses: ./gcp-secret-manager
+        with:
+          service-account-key: ${{ secrets.SECRET_AUTH }}
+          secrets: |
+            TEST_TOKEN: sonarqube-token
+            NEXUS_USER: nexus-username
+            TEST2_TOKEN: sonarqube-token
+
+      - name: Assert GCP secrets
+        shell: bash
+        run: |
+          if [ -n "$TEST_TOKEN" ]; then
+            echo "Secret successfully set to env"
+          else
+            echo "Failed to set secret to env"
+            exit 1
+          fi
+
+          if [ "$NEXUS_USER" = "${{ secrets.NEXUS_USERNAME }}" ]; then
+            echo "Secret matches expectation"
+          else
+            echo "Secrets does not match"
+            exit 1
+          fi
+
+          if [ "$TEST_TOKEN" = "$TEST2_TOKEN" ]; then
+            echo "Secret matches expectation"
+          else
+            echo "Second secret does not match"
+            exit 1
+          fi
+
   acceptance-linux:
     runs-on: ubuntu-latest
     needs:
@@ -142,6 +175,8 @@ jobs:
           service-account-key: ${{ secrets.SECRET_AUTH }}
           secrets: |
             TEST_TOKEN: sonarqube-token
+            NEXUS_USER: nexus-username
+            TEST2_TOKEN: sonarqube-token
 
       - name: Assert GCP secrets
         run: |
@@ -149,6 +184,20 @@ jobs:
             echo "Secret successfully set to env"
           else
             echo "Failed to set secret to env"
+            exit 1
+          fi
+
+          if [ "$NEXUS_USER" = "${{ secrets.NEXUS_USERNAME }}" ]; then
+            echo "Secret matches expectation"
+          else
+            echo "Secrets does not match"
+            exit 1
+          fi
+
+          if [ "$TEST_TOKEN" = "$TEST2_TOKEN" ]; then
+            echo "Secret matches expectation"
+          else
+            echo "Second secret does not match"
             exit 1
           fi
 
